name: file_converter
description: "A new Flutter project for file conversions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Core Functionality
  file_picker: ^6.1.1
  nyx_converter: ^0.0.6
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  syncfusion_flutter_pdf: ^25.1.39
  path_provider: ^2.1.1

  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
